config:
  luxel-vercel:gitRepo: rielicat/luxel-services-monorepo
  luxel-vercel:productionBranch: main
  luxel-vercel:teamId: ''
  luxel-vercel:web:
    name: REPLACE_WITH_WEB_PROJECT_NAME
    rootDirectory: apps/web
  luxel-vercel:admin:
    name: luxel-admin
    rootDirectory: apps/admin
    domain: admin.serviciosluxel.cl
