config:
  luxel-cloudflare:accountId: a592f6c9ed79454bf7c8ab489ece9036
  luxel-cloudflare:zoneId: 5f63078a62ac7516e60d81be7c692dd2
  luxel-cloudflare:zoneName: serviciosluxel.cl
  luxel-cloudflare:vercelTarget: ae0aca0ff9e30f31.vercel-dns-017.com
  luxel-cloudflare:adminTarget: cname.vercel-dns.com
  luxel-cloudflare:clerkMailHash: dw7l996s5zgh
  luxel-cloudflare:dmarcPolicy: none
  luxel-cloudflare:emailRouting:
    enabled: true
    destinations:
      - catrielguillen@gmail.com
    rules:
      - address: catriel@serviciosluxel.cl
        forwardTo: catrielguillen@gmail.com
      - address: info@serviciosluxel.cl
        forwardTo: catrielguillen@gmail.com
    catchAll:
      enabled: true
      action: drop
      forwardTo: []
encryptionsalt: v1:o4W2HeoOLYY=:v1:RYTASX6j0agRx34L:vdGf+yDSzY/XCipOCZjR1Bi2QaLpzQ==
